package com.avaricious.utility;

public enum AssetKey {
    WHITE_PIXEL("white"),
    BUTTON_BOARD("buttonboard"),
    BUTTON_BOARD_SHADOW("buttonboard-shadow"),
    SPIN_AGAIN_BUTTON("spin-again"),
    SPIN_AGAIN_BUTTON_DISABLED("spin-again-disabled"),
    SPIN_AGAIN_BUTTON_HOVERED("spin-again-hovered"),
    SPIN_AGAIN_BUTTON_PRESSED("spin-again-pressed"),
    CASHOUT_BUTTON("cashout"),
    CASHOUT_BUTTON_DISABLED("cashout-disabled"),
    CASHOUT_BUTTON_HOVERED("cashout-hovered"),
    CASHOUT_BUTTON_PRESSED("cashout-pressed"),
    ZERO_NUMBER("0"),
    ONE_NUMBER("1"),
    TWO_NUMBER("2"),
    THREE_NUMBER("3"),
    FOUR_NUMBER("4"),
    FIVE_NUMBER("5"),
    SIX_NUMBER("6"),
    SEVEN_NUMBER("7"),
    EIGHT_NUMBER("8"),
    NINE_NUMBER("9"),
    ZERO_NUMBER_SHADOW("0-shadow"),
    ONE_NUMBER_SHADOW("1-shadow"),
    TWO_NUMBER_SHADOW("2-shadow"),
    THREE_NUMBER_SHADOW("3-shadow"),
    FOUR_NUMBER_SHADOW("4-shadow"),
    FIVE_NUMBER_SHADOW("5-shadow"),
    SIX_NUMBER_SHADOW("6-shadow"),
    SEVEN_NUMBER_SHADOW("7-shadow"),
    EIGHT_NUMBER_SHADOW("8-shadow"),
    NINE_NUMBER_SHADOW("9-shadow"),
    MULT_SYMBOL("mult"),
    MULT_SYMBOL_SHADOW("mult-shadow"),
    PLUS_SYMBOL("plus"),
    PLUS_SYMBOL_SHADOW("plus-shadow"),
    DARK_GREEN_PIXEL("dark-green"),
    PROGRESS_BAR_BORDER("ProgressBarBorder"),
    PROGRESS_BAR_LIT("ProgressBarLit"),
    PROGRESS_BAR_UNLIT("ProgressBarUnlit"),
    PERCENTAGE_SYMBOL("percentage"),
    TOOLTIP_BOX("TooltipBox"),
    TOOLTIP_BOX_SHADOW("TooltipBox-shadow"),
    HEART("heart"),
    HEALTH_RED_PIXEL("health-red-pixel"),
    SHOP_WINDOW("ShopWindow"),
    SHOP_WINDOW_SHADOW("ShopWindowShadow"),
    SHOP_TXT("ShopTxt"),
    SHOP_TXT_SHADOW("ShopTxt-shadow"),
    REROLL_BUTTON("reroll"),
    REROLL_BUTTON_HOVERED("reroll-hovered"),
    REROLL_BUTTON_PRESSED("reroll-pressed"),
    RETURN_BUTTON("return"),
    RETURN_BUTTON_HOVERED("return-hovered"),
    RETURN_BUTTON_PRESSED("return-pressed"),
    DOLLAR_SYMBOL("dollar"),
    LEMON("lemon"),
    CHERRY("cherry"),
    CLOVER("clover"),
    BELL("bell"),
    IRON("iron"),
    DIAMOND("diamond"),
    SEVEN("seven"),
    SLOT_BOX("slotBox"),
    SLOT_BOX_SHADOW("slotBox-shadow"),
    BLACK_GREEN_PIXEL("black-green-pixel"),
    STATUS_UPGRADE_WINDOW("UpgradeWindow"),
    STATUS_UPGRADE_WINDOW_SHADOW("UpgradeWindow-shadow"),
    LEVEL_UP_TEXT("levelup"),
    SHOP_BUTTON("shop"),
    SHOP_BUTTON_HOVERED("shop-hovered"),
    SHOP_BUTTON_PRESSED("shop-pressed"),
    XP_PIXEL("xp-pixel"),
    EMPTY_PIXEL("empty-pixel"),
    JOKER_CARD("Joker"),
    JOKER_CARD_SHADOW("JokerShadow"),
    POKER_CHIP("base-poker-chip"),
    POKER_CHIP_SHADOW("base-poker-chip-shadow"),
    COIN("coin"),
    COIN_SHADOW("coin-shadow"),
    CRITICAL_HIT("critical hit"),
    CRITICAL_HIT_SHADOW("critical hit-shadow"),
    RETRIGGER("Retrigger"),
    RETRIGGER_SHADOW("Retrigger-shadow"),
    EVADE("evade"),
    EVADE_SHADOW("evade-shadow"),
    LUCK("luck"),
    LUCK_SHADOW("luck-shadow"),
    MULTI("multi"),
    MULTI_SHADOW("multi-shadow"),
    GREY_PIXEL("grey-pixel"),
    LIGHT_GREY_PIXEL("light-grey-pixel"),
    BUTTON_SHADOW("button-shadow"),
    DARK_BLUE_PIXEL("dark-blue-pixel"),
    BLUE_GREEN_PIXEL("blue-green-pixel"),
    YELLOW_PIXEL("yellowPixel"),
    ARMOR_ICON("armor"),
    SILVER_PIXEL("silver-pixel"),
    MINUS_SYMBOL("minus-symbol"),
    DUMPSTER_OPENED("Dumpster0"),
    DUMPSTER_1("Dumpster1"),
    DUMPSTER_2("Dumpster2"),
    DUMPSTER_3("Dumpster3"),
    DUMPSTER_4("Dumpster4"),
    DUMPSTER_CLOSED("Dumpster5"),
    DUMPSTER_SHADOW("dumpster-shadow"),
    DARK_RED_PIXEL("dark-red-pixel"),
    SLATE_PIXEL("slate-pixel"),
    DARK_SLATE_PIXEL("dark-slate-pixel"),
    BRIGHT_SLATE_PIXEL("bright-slate-pixel"),
    BLACK_BLUE_PIXEL("black-blue-pixel"),
    SPIN_BUTTON("spin-button"),
    SPIN_BUTTON_PRESSED("spin-button-pressed"),
    DARK_STEEL_PIXEL("dark-steel-pixel");

    private final String path;

    AssetKey(String path) {
        this.path = path;
    }

    public String path() {
        return path;
    }
}
