package com.avaricious;

public enum AssetKey {
    WHITE_PIXEL("white"),
    BUTTON_BOARD("buttonboard"),
    BUTTON_BOARD_SHADOW("buttonboard-shadow"),
    SPIN_AGAIN_BUTTON("spin-again"),
    SPIN_AGAIN_BUTTON_DISABLED("spin-again-disabled"),
    SPIN_AGAIN_BUTTON_HOVERED("spin-again-hovered"),
    SPIN_AGAIN_BUTTON_PRESSED("spin-again-pressed"),
    CASHOUT_BUTTON("cashout"),
    CASHOUT_BUTTON_DISABLED("cashout-disabled"),
    CASHOUT_BUTTON_HOVERED("cashout-hovered"),
    CASHOUT_BUTTON_PRESSED("cashout-pressed"),
    ZERO_NUMBER("0"),
    ONE_NUMBER("1"),
    TWO_NUMBER("2"),
    THREE_NUMBER("3"),
    FOUR_NUMBER("4"),
    FIVE_NUMBER("5"),
    SIX_NUMBER("6"),
    SEVEN_NUMBER("7"),
    EIGHT_NUMBER("8"),
    NINE_NUMBER("9"),
    MULT_SYMBOL("mult"),
    MULT_SYMBOL_SHADOW("mult-shadow"),
    PLUS_SYMBOL("plus"),
    PLUS_SYMBOL_SHADOW("plus-shadow"),
    DARK_GREEN_PIXEL("dark-green"),
    PROGRESS_BAR_BORDER("ProgressBarBorder"),
    PROGRESS_BAR_LIT("ProgressBarLit"),
    PROGRESS_BAR_UNLIT("ProgressBarUnlit"),
    PERCENTAGE_SYMBOL("percentage"),
    TOOLTIP_BOX("TooltipBox"),
    TOOLTIP_BOX_SHADOW("TooltipBox-shadow"),
    HEART("heart"),
    HEALTH_RED_PIXEL("health-red-pixel"),
    SHOP_WINDOW("ShopWindow"),
    REROLL_BUTTON("reroll"),
    REROLL_BUTTON_HOVERED("reroll-hovered"),
    REROLL_BUTTON_PRESSED("reroll-pressed"),
    RETURN_BUTTON("return"),
    RETURN_BUTTON_HOVERED("return-hovered"),
    RETURN_BUTTON_PRESSED("return-pressed"),
    DOLLAR_SYMBOL("dollar"),
    LEMON("lemon"),
    CHERRY("cherry"),
    CLOVER("clover"),
    BELL("bell"),
    IRON("iron"),
    DIAMOND("diamond"),
    SEVEN("seven"),
    SLOT_BOX("slotBox"),
    SLOT_BOX_SHADOW("slotBox-shadow"),
    BLACK_GREEN_PIXEL("black-green-pixel"),
    STATUS_UPGRADE_WINDOW("UpgradeWindow"),
    STATUS_UPGRADE_WINDOW_SHADOW("UpgradeWindow-shadow"),
    LEVEL_UP_TEXT("levelup"),
    SHOP_BUTTON("shop"),
    SHOP_BUTTON_HOVERED("shop-hovered"),
    SHOP_BUTTON_PRESSED("shop-pressed"),
    XP_PIXEL("xp-pixel"),
    EMPTY_PIXEL("empty-pixel"),
    JOKER_CARD("Joker"),
    JOKER_CARD_SHADOW("JokerShadow"),
    POKER_CHIP("base-poker-chip"),
    POKER_CHIP_SHADOW("base-poker-chip-shadow"),
    COIN("coin"),
    COIN_SHADOW("coin-shadow"),
    CRITICAL_HIT("critical hit"),
    CRITICAL_HIT_SHADOW("critical hit-shadow"),
    RETRIGGER("Retrigger"),
    RETRIGGER_SHADOW("Retrigger-shadow"),
    EVADE("evade"),
    EVADE_SHADOW("evade-shadow"),
    LUCK("luck"),
    LUCK_SHADOW("luck-shadow"),
    MULTI("multi"),
    MULTI_SHADOW("multi-shadow"),
    GREY_PIXEL("grey-pixel");

    private final String path;

    AssetKey(String path) {
        this.path = path;
    }

    public String path() {
        return path;
    }
}
